### ISSUE TITLE
Here is v2.4.2

### ISSUE THREAD

**Issue by szepeviktor** [chesio/add-meta-tags#1]
https://github.com/vthierry/wordpress-add-meta-tags

**Comment by szepeviktor** [comment]
I see! 2.11.3 is later.

**Comment by chesio** [comment]
Thanks @szepeviktor - I should perhaps look for existing forks first, but I'm not going to make any big changes anyway, mainly make sure the plugin still runs on PHP 8...

**Comment by szepeviktor** [comment]
This plugin is very close to a script. Flowing statements.
It needs a rewrite to be application-like.
